#!/usr/bin/env node

/**
 * Build .env.local for local development, pulling real values from 1Password.
 *
 *   pnpm setup:secrets
 *
 * Resolves the `dev` field of each 1Password item. Production values are never
 * written to disk — `pnpm push:secrets --prod` reads them straight from
 * 1Password and sends them to the deployment.
 *
 * ── Why this isn't just `op inject` ────────────────────────────────────────
 * `op inject -i .env.example -o .env.local` OVERWRITES the output file.
 * .env.local also holds CONVEX_DEPLOYMENT and CONVEX_URL, written by
 * `npx convex dev`, which identify your backend — so a plain inject silently
 * disconnects you from your own deployment, and the breakage looks nothing
 * like its cause. This merges instead.
 */

const { existsSync, readFileSync, writeFileSync } = require("node:fs");
const {
  LOCAL_PATH,
  parseEnv,
  reportProblems,
  requireOpCli,
  resolveTemplate,
} = require("./lib/secrets");

requireOpCli();

const { values, missing, ambiguous } = resolveTemplate("dev");

if (missing.length > 0 || ambiguous.length > 0) {
  reportProblems({ missing, ambiguous });
  console.error("Nothing was written — .env.local is unchanged.\n");
  process.exit(1);
}

const existing = existsSync(LOCAL_PATH)
  ? parseEnv(readFileSync(LOCAL_PATH, "utf-8"))
  : new Map();

const merged = new Map(existing);
for (const [key, value] of values) merged.set(key, value);

// See the note in .env.example: keeping this alongside CONVEX_URL makes the
// Convex CLI refuse to keep the deployment URL up to date.
merged.delete("EXPO_PUBLIC_CONVEX_URL");

const body = [
  "# Generated by `pnpm setup:secrets`. Do not commit — this file holds real secrets.",
  "# CONVEX_* values come from `npx convex dev` and are preserved on regeneration.",
  "",
  ...[...merged].map(([key, value]) => `${key}=${value}`),
  "",
].join("\n");

writeFileSync(LOCAL_PATH, body, { mode: 0o600 });

console.log(`Wrote .env.local — ${values.size} value(s), dev environment.`);
const convexUrl = merged.get("CONVEX_URL");
if (convexUrl) console.log(`Convex deployment preserved: ${convexUrl}`);
console.log("\nNext: pnpm push:secrets   (values live on the deployment, not here)");
